[package]
name = "nasl-sys"
version = "0.0.1"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
log = "0.4"
libc = "^0.2"
glib = "^0.6"
glib-sys = "^0.7"


[build-dependencies]
